#+nil
(setf autowrap:*c2ffi-program* "/home/ancient/c2ffi/build/bin/c2ffi")

(autowrap:c-include
 (asdf:system-relative-pathname :cimgui-autowrap "src/cimgui-autowrap.h")
 :spec-path '(cimgui-autowrap spec)
 :definition-package :ig
 :c-to-lisp-function (lambda (s)
                       (let ((s (autowrap:default-c-to-lisp s)))
                         (ppcre:regex-replace "^IG-" s "")))
 ;; nil だと autowrap がとおらない
 :no-accessors t
 :no-functions nil
 :release-p t
 :symbol-exceptions
 (("igAcceptDragDropPayload" . "%ACCEPT-DRAG-DROP-PAYLOAD")
  ("igBegin" . "%BEGIN")
  ("igBeginPopupContextItem" . "%BEGIN-POPUP-CONTEXT-ITEM")
  ("igBeginPopupModal" . "%BEGIN-POPUP-MODAL")
  ("igButton" . "%BUTTON")
  ("igCalcTextSize" . "%CALC-TEXT-SIZE")
  ("igCheckbox" . "%CHECKBOX")
  ("igColorPicker4" . "%COLOR-PICKER4")
  ("igDummy" . "%DUMMY")
  ("igGetCursorPos" . "%GET-CURSOR-POS")
  ("igGetDragDropPayload" . "%GET-DRAG-DROP-PAYLOAD")
  ("igGetItemRectMax" . "%GET-ITEM-RECT-MAX")
  ("igGetItemRectMin" . "%GET-ITEM-RECT-MIN")
  ("igGetItemRectSize" . "%GET-ITEM-RECT-SIZE")
  ("igGetMousePos" . "%GET-MOUSE-POS")
  ("igGetWindowPos" . "%GET-WINDOW-POS")
  ("igGetWindowSize" . "%GET-WINDOW-SIZE")
  ("igDragFloat" . "%DRAG-FLOAT")
  ("igDragScalar" . "%DRAG-SCALAR")
  ("igInputDouble" . "%INPUT-DOUBLE")
  ("igInvisibleButton" . "%INVISIBLE-BUTTON")
  ("igIsItemActive" . "%IS-ITEM-ACTIVE")
  ("igIsItemHovered" . "%IS-ITEM-HOVERED")
  ("igIsMouseDragging" . "%IS-MOUSE-DRAGGING")
  ("igIsWindowAppearing" . "%IS-WINDOW-APPEARING")
  ("igIsWindowHovered" . "%IS-WINDOW-HOVERED")
  ("igPushClipRect". "%PUSH-CLIP-RECT")
  ("igSameLine" . "%SAME-LINE")
  ("igSetCursorPos" . "%SET-CURSOR-POS")
  ("igSetDragDropPayload" . "%SET-DRAG-DROP-PAYLOAD")
  ("igSetKeyboardFocusHere" . "%SET-KEYBOARD-FOCUS-HERE")
  ("igSetNextItemShortcut" . "%SET-NEXT-ITEM-SHORTCUT")
  ("igSetNextWindowSizeConstraints" . "%SET-NEXT-WINDOW-SIZE-CONSTRAINTS")
  ("igSliderFloat" . "%SLIDER-FLOAT")
  ("igVSliderFloat" . "%V-SLIDER-FLOAT")
  ("igVSliderScalar" . "%V-SLIDER-SCALAR")))
